import 'dart:developer';

import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:phrasly_ai_tools/src/core/network/ai_api/models/text_analysis_model.dart';
import 'package:phrasly_ai_tools/src/core/network/models/app_error.dart';
import 'package:phrasly_ai_tools/src/core/services/storage/humanized_text_storage_service.dart';
import 'package:phrasly_ai_tools/src/features/detector/data/repos/detector_repo.dart';
import 'package:phrasly_ai_tools/src/features/detector/presentation/pages/detector_page.dart';

part 'detector_state.dart';
part 'gen/detector_cubit.freezed.dart';

class DetectorCubit extends Cubit<DetectorState> {
  final DetectorRepo _detectorRepo;

  DetectorCubit(this._detectorRepo) : super(const DetectorState.initial());

  Future<void> analyzeText(String text, {required DetectorModes mode}) async {
    if (text.trim().isEmpty) {
      emit(DetectorState.error(AppError.server(message: 'Please enter some text to analyze')));
      return;
    }

    // Check if we have a cached result for this text
    final cachedHumanPercentage = HumanizedTextStorageService.getCachedHumanPercentage(text);

    if (cachedHumanPercentage != null) {
      log('DetectorCubit - Using cached detection result: $cachedHumanPercentage% human');

      // Create a TextAnalysisResult from cached data
      final cachedResult = TextAnalysisResult(
        source: _getTextSource(cachedHumanPercentage),
        humanProbability: cachedHumanPercentage / 100,
        explanation:
            'This text displays a range of natural expressions, unique phrasing, and human-like thought progression, indicating it was likely generated by a person.',
      );

      await Future.delayed(const Duration(seconds: 2));

      emit(DetectorState.loaded(cachedResult));
      return;
    }

    emit(const DetectorState.loading());

    final result = await _detectorRepo.analyzeText(text: text, mode: mode);

    result.fold(
      (error) => emit(DetectorState.error(error)),
      (analysisResult) => emit(DetectorState.loaded(analysisResult)),
    );
  }

  /// Determine text source based on human percentage
  /// High human % (>=70) = Human, Low human % (<=30) = AI
  TextSource _getTextSource(double humanPercentage) {
    if (humanPercentage >= 70) return TextSource.human;
    if (humanPercentage <= 30) return TextSource.ai;
    return TextSource.mixed;
  }

  void reset() {
    emit(const DetectorState.initial());
  }
}
