name: phrasly_ai_tools
description: "A new Flutter project."

publish_to: "none"

version: 1.0.2+20

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  collection: ^1.18.0
  connectivity_plus: ^6.1.4
  crypto: ^3.0.5
  device_info_plus: ^11.3.0
  dotted_border: ^2.1.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  firebase_auth: ^5.5.1
  firebase_remote_config: ^5.5.0
  firebase_crashlytics: ^4.3.10
  firebase_analytics: ^11.6.0
  google_sign_in: ^6.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: 19.0.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0
  fpdart: ^1.1.1
  get_it: ^8.0.3
  go_router: ^14.8.1
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  internet_connection_checker: ^3.0.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  fluttertoast: ^8.2.12
  logger: ^2.5.0
  package_info_plus: ^8.3.0
  permission_handler: ^11.4.0
  purchases_ui_flutter: ^8.0.0
  restart_app: ^1.3.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  top_snackbar_flutter: ^3.2.0
  upgrader:
    git: https://github.com/anokabb/upgrader
  url_launcher: ^6.3.1
  validators: ^3.0.0
  google_fonts: ^6.2.1
  dio: ^5.8.0+1
  equatable: ^2.0.5
  retrofit:
  pin_code_fields: ^8.0.1
  freezed_annotation: ^2.4.4
  path_provider: ^2.1.4
  pdf: ^3.10.7
  printing: ^5.11.1
  share_plus: ^7.2.2
  curved_navigation_bar: ^1.0.6
  circle_nav_bar: ^2.2.0
  flutter_markdown: ^0.6.18
  in_app_review: ^2.0.11
  appsflyer_sdk: ^6.17.5
  mixpanel_flutter: ^2.4.4
  clarity_flutter: ^1.4.1
  webview_flutter: ^4.13.0
  file_picker: ^10.3.3
  read_pdf_text: ^0.3.1
  google_mlkit_text_recognition: ^0.15.0
  doc_text_extractor: ^1.0.0
  app_tracking_transparency: ^2.0.6+1

dev_dependencies:
  build_runner: null
  flutter_gen_runner: ^5.10.0
  flutter_launcher_icons: any
  flutter_lints: ^5.0.0
  flutter_native_splash: any
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
  freezed: ^2.5.7
  retrofit_generator:

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/images/onboarding/profiles/
    - assets/svg/

flutter_gen:
  output: lib/src/core/gen
  line_length: 150

# fvm dart run flutter_launcher_icons
flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/images/app_icon.png"

# fvm dart run flutter_native_splash:create
flutter_native_splash:
  color: "#CEDFF3"
  image: assets/images/app_splash.png
  android_12:
    color: "#CEDFF3"
    image: "assets/images/app_splash_android_12.png"
  android: true
  ios: true
